app/Config/__init__.py
from flask import Blueprint

bp = Blueprint('config',__name__)

from app.Config import routes

app/Config/routes.py
from app.Config import bp
from app.forms.cron_job_config import CronJobConfig
from app.forms.mail_config import MailConfig
from flask import render_template, redirect
from scrape_script.task import task
from app.extensions import scheduler, db
from app.models.mail_config import mail_config
from sqlalchemy.exc import NoResultFound


@bp.route('/config', methods=['GET'])
def config():
    try:
        mail_configuration = mail_config.query.one()
    except NoResultFound:
        mail_configuration = None
    current_job = scheduler.get_job('daily_task')
    form_scheduler = CronJobConfig()
    form_mail = MailConfig()
    hour = None
    minute = None
    if mail_configuration:
        form_mail.notification_email.data = mail_configuration.notification_email
        form_mail.notification_receivers_email.data = mail_configuration.notification_receivers_email
        form_mail.notification_pass.data = mail_configuration.notification_pass
        form_mail.notification_smtp_server.data = mail_configuration.notification_smtp_server
    if current_job:
        for f in current_job.trigger.fields:
            if f.name == 'hour':
                hour = f
            if f.name == 'minute':
                minute = f
        form_scheduler.hour.data = str(hour)
        form_scheduler.minute.data = str(minute)
    return render_template('config.html', current_job = current_job,form_scheduler=form_scheduler,form_mail=form_mail, hour=hour, minute = minute,
                           mail_configuration=mail_configuration)


@bp.route('/process_scheduler_config', methods=['POST'])
def process_scheduler_config_form():
    form_scheduler = CronJobConfig()
    current_job = scheduler.get_job('daily_task')

    if form_scheduler.enable_job.data and not current_job:
        hour = form_scheduler.hour.data
        minute = form_scheduler.minute.data
        scheduler.add_job(id='daily_task', func=task, trigger='cron', hour=hour, minute=minute)
        scheduler.start()
        return redirect('/config')
    elif form_scheduler.enable_job.data and current_job:
        hour = form_scheduler.hour.data
        minute = form_scheduler.minute.data
        scheduler.modify_job(id='daily_task',hour=hour, minute=minute)
        return redirect('/config')
    elif not form_scheduler.enable_job.data and not current_job:
        return redirect('/config')
    else: 
        scheduler.remove_job(id='daily_task')
        scheduler.shutdown()
        return redirect('/config')

@bp.route('/process_mail_config', methods=['POST'])
def process_mail_config_form():
    form_mail = MailConfig()
    try:
        mail_config_in_db = mail_config.query.one()
        mail_config_in_db.notification_email=form_mail.data['notification_email']
        mail_config_in_db.notification_receivers_email=form_mail.data['notification_receivers_email']
        mail_config_in_db.notification_pass=form_mail.data['notification_pass']
        mail_config_in_db.notification_smtp_server=form_mail.data['notification_smtp_server']
        db.session.commit()
    except NoResultFound:
        new_mail_config = mail_config(notification_email=form_mail.data['notification_email'],notification_receivers_email=form_mail.data['notification_receivers_email'],
                                      notification_pass=form_mail.data['notification_pass'],notification_smtp_server=form_mail.data['notification_smtp_server'])
        db.session.add(new_mail_config)
        db.session.commit()
    return redirect('/config')

app/insert/__init__.py
from flask import Blueprint

bp = Blueprint('insert', __name__)

from app.insert import routes

app/insert/routes.py
from flask import render_template, redirect, request
from app.insert import bp
from app.forms.new_param_form import New_param_form
from app.extensions import db
from app.models.search_params import Search_param
from helpers.countries_getter import update_country


@bp.route('/insert',methods=['GET',"POST"])
def insert_new_param():
    form = New_param_form()
    form.country.choices = update_country()
    if request.method == 'POST' and form.validate_on_submit():
        new_param = Search_param(
            country = form.country.data,
            date_from = form.date_from.data,
            date_to = form.date_to.data,
            stay_length = form.stay_length_slider.data,
            stars = form.stars.data,
            max_price = form.max_price.data,
            transportation = form.transportation.data,
            amenities = form.amenities.data,
            departure_city = form.departure_city.data,
            rating = form.rating.data
        )
        db.session.add(new_param)
        db.session.commit()
        return redirect("/list")
    return render_template('insert.html',form=form)

@bp.route('/insert/<int:paramid>',methods=['GET',"POST"])
def edit_existing_param(paramid):
    param_to_edit = db.session.query(Search_param).get(paramid)
    form = New_param_form(obj=param_to_edit)
    form.country.choices = update_country()
    if request.method == 'POST' and form.validate_on_submit():
        param_to_edit.country = form.country.data
        param_to_edit.date_from = form.date_from.data
        param_to_edit.date_to = form.date_to.data
        param_to_edit.stay_length = form.stay_length_slider.data
        param_to_edit.stars = form.stars.data
        param_to_edit.max_price = form.max_price.data
        param_to_edit.transportation = form.transportation.data
        param_to_edit.amenities = form.amenities.data
        param_to_edit.departure_city = form.departure_city.data
        param_to_edit.rating = form.rating.data
        db.session.commit()
        return redirect("/list")
    return render_template('insert.html',form=form)

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}Vacation search app{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
<script src="{{ url_for('static', filename='js/index.js') }}"></script>

</head>
<body>

  <div class="topnav">
    <a class="{% if request.endpoint == 'main.index' %}active{% endif %}" href="{{ url_for('main.index') }}">Home</a>
    <a class="{% if request.endpoint == 'list.list_of_params' %}active{% endif %}" href="{{ url_for('list.list_of_params')}}">List all search params</a>
    <a class="{% if request.endpoint == 'insert.insert_new_param' %}active{% endif %}" href="{{ url_for('insert.insert_new_param')}}">Insert new param</a>
    <a class="{% if request.endpoint == 'config.config' %}active{% endif %}" href="{{ url_for('config.config')}}">Config</a>
  </div>


<main>{% block content %}{% endblock %}</main>

</body>
</html>

app/templates/config.html
{% extends "base.html" %}

{% block content %}

<div style="padding-left:16px">
    <h2 class="config-aligned-table">Scheduler config</h2>
  </div>

  <table class="config-aligned-table">
    <tr>
      <th>Property</th>
      <th>Value</th>
    </tr>
    <tr>
      <td>Is On</td>
      <td>{% if current_job %} True {% else %} False {% endif %}</td>
    </tr>
    <tr>
      <td>Hour</td>
      <td>{% if current_job %} {{ hour }} {% endif %}</td>
  
    </tr>
      <tr>
      <td>Minute</td>
      <td>{% if current_job %} {{ minute }} {% endif %}</td>
  
    </tr>
  </table> 
  <br>
  <form class="config-aligned-table" method="POST" action="{{ url_for('config.process_scheduler_config_form') }}">
    {{ form_scheduler.csrf_token }}
    {{ form_scheduler.enable_job.label }}
    {{ form_scheduler.enable_job }}
    <br>
    {{ form_scheduler.hour.label }}
    {{ form_scheduler.hour }}
    {{ form_scheduler.minute.label }}
    {{ form_scheduler.minute }}
    {{ form_scheduler.submit }}
  </form>

  <h2 class="config-aligned-table">Mail config</h2>

  <table class="config-aligned-table">
    <tr>
      <th>Property</th>
      <th>Value</th>
    </tr>
    <tr>
      <td>Notification email</td>
      <td>{% if mail_configuration %} {{ mail_configuration.notification_email }} {% else %} Null {% endif %}</td>
    </tr>
    <tr>
      <td>Notification receivers email</td>
      <td>{% if mail_configuration %} {{ mail_configuration.notification_receivers_email }} {% else %} Null {% endif %}</td>
    </tr>
    <tr>
      <td>Notification pass</td>
      <td>{% if mail_configuration %} {{ mail_configuration.notification_pass }} {% else %} Null {% endif %}</td>
    </tr>
      <tr>
        <td>Notification smtp server</td>
        <td>{% if mail_configuration %} {{ mail_configuration.notification_smtp_server }} {% else %} Null {% endif %}</td>
      </tr>
  </table>

  <p class="config-aligned-table">List receivers emails in format: email@foo.foo,mail2@foo.foo</p>

  <form class="config-aligned-table" method="POST" action="{{ url_for('config.process_mail_config_form') }}">
    {{form_mail.csrf_token}}
    {{form_mail.notification_email.label}}
    {{form_mail.notification_email}}
    {{ form_mail.notification_receivers_email.label }}
    {{ form_mail.notification_receivers_email }}
    {{ form_mail.notification_pass.label }}
    {{ form_mail.notification_pass }}
    {{ form_mail.notification_smtp_server.label }}
    {{ form_mail.notification_smtp_server }}
    {{ form_mail.submit }}
  </form>

  {% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}

<div style="padding-left:16px">
    <h2>Currently present search params:</h2>
    <p>{{params_count}}</p>
    <h2>Last succesful search: </h2>
    <p>TBC</p>
    <h2>Last succesful email send: </h2>
    <p>TBC</p>
  </div>
  <div>
    <button onclick="ActivateScript()">Activate Script</button>
  </div>

  {% endblock %}

app/templates/insert.html
{% extends "base.html" %}

{% block content %}
<br>

<form method="POST">
  {{ form.csrf_token }}
  {{form.country.label}}<br>
  {{form.country}}<br>
  {{form.date_from.label}}<br>
  {{form.date_from}}<br>
  {{form.date_to.label}}<br>
  {{form.date_to}}<br>
  {{form.stay_length_slider.label}}<br>
  <input type="range" id="stay_lenght_from" min="1" max="28" value="1" oninput="updateSliderValue()"><br>
  <input type="range" id="stay_lenght_to" min="1" max="28" value="28" oninput="updateSliderValue()"><br>
  <input type="text" name="stay_length_slider" id="stay_lenght_id" value="{{ form.stay_length_slider.data }}">
  {{form.stars.label}}<br>
  {{form.stars}}<br>
  {{form.max_price.label}}<br>
  {{form.max_price}}<br>
  {{form.transportation.label}}<br>
  {{form.transportation}}<br>
  {{form.amenities.label}}<br>
  {{form.amenities}}<br>
  {{form.departure_city.label}}<br>
  {{form.departure_city}}<br>
  {{form.rating.label}}<br>
  {{form.rating}}<br>
  {{form.submit}}

</form>

{% endblock %}

app/templates/list_of_params.html
{% extends "base.html" %}

{% block content %}


<h1>Search Params Data</h1>

<table>
    <thead>
        <tr>
            <th>Country</th>
            <th>Date From</th>
            <th>Date To</th>
            <th>Stay Length</th>
            <th>Stars</th>
            <th>Max Price</th>
            <th>Transportation</th>
            <th>Amenities</th>
            <th>Departure City</th>
            <th>Rating</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for result in params_list %}
            <tr>
                <td>{{ result.country }}</td>
                <td>{{ result.date_from }}</td>
                <td>{{ result.date_to }}</td>
                <td>{{ result.stay_length }}</td>
                <td>{{ result.stars }}</td>
                <td>{{ result.max_price }}</td>
                <td>{{ result.transportation }}</td>
                <td>{{ result.amenities }}</td>
                <td>{{ result.departure_city }}</td>
                <td>{{ result.rating }}</td>
                <td><button onclick="EditSearchParam({{result.id}})">Edit</button></td>
                <td><button onclick="DeleteSearchParam({{ result.id }})">Delete</button></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}